export FFTW_UTIL_INSTALL_DIR=/Users/linda/ANITA/anita3/anitaBuildTool/utils
export FFTW_UTIL_INC_DIR=${FFTW_UTIL_INSTALL_DIR}/include
export DYLD_LIBRARY_PATH=${FFTW_UTIL_INSTALL_DIR}/lib:${DYLD_LIBRARY_PATH}
export PATH=${FFTW_UTIL_INSTALL_DIR}/bin:${PATH}
